# PostgreSQL - Render (Conecta2)
spring.datasource.url=jdbc:postgresql://dpg-d4caams9c44c738mlkv0-a.oregon-postgres.render.com:5432/db_conecta2?sslmode=require
spring.datasource.username=admin
spring.datasource.password=K4oVOUVWuSjwPi3QRAoXLUb87kmrqppn
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true␊
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true␊
spring.jpa.properties.hibernate.default_schema=public

# Mail (si usas Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=appconecta2.services@gmail.com
spring.mail.password=dcwp qvis qagu glii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=3000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT
app.jwt.secret=K1C9bQmQmK0H1rJ2vQm8k9Qqv0tQkL6Kc6k0x8y2u3a1p5N7k4m2w==
app.jwt.access.exp-min=60
app.jwt.activation.exp-min=15

# JSON formato ISO-8601
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
spring.jackson.time-zone=UTC

# URL base (local)
app.base-url=http://localhost:8080


# Mail y activacion
app.mail.enabled=true
# false => no auto-activa, envia correo de verificacion
app.activation.auto=false

